[package]
name = "swiffer"
version = "0.1.0"
edition = "2021"

[lib]
name = "packet_swiffer"
path = "src/lib/lib.rs"

[dependencies]
dns-parser = "0.8.0"
cursive = "0.20.0"

[dependencies.pnet]
version = "0.30.0"
